### ISSUE TITLE
Slightly confused how this package is supposed to work

### ISSUE THREAD

**Issue by elie222** [kaskar2008/tgauth#6]
Hi,

Trying to get the package working, but not really sure what I'm supposed to be doing with it. What's the python code here for? And what does the user have to do within a Telegram chat to get authenticated?

**Comment by kaskar2008** [comment]
First of all - you need to create a telegram bot (on js, python, whatever language you choose) which will receive `BOT_CODE` and tell it and your telegram username and ID to your server (app).

**Comment by kaskar2008** [comment]
First of all - you need to create a telegram bot (on js, python, whatever language you choose) which will receive BOT_CODE and tell it and your telegram username and ID to your server (app).
Bot should also have an access token to prevent sending queries from other bots. It's up to you to dicide how long and hard your access token will be.
Next you should make, I don't know, a button which will start a feature `Meteor.telegramStartLogin();`
Ex:
`Template.hello.events({
        "click button": function (event) {
            Meteor.telegramStartLogin();
        }
    });`
After this `{{TGloginCode}}` helper will contains that `BOT_CODE` which user have to send to your bot (It's up to you how to manage it on the bot side. For example you could make a command like this: `/login $YOUR_CODE$`). Then bot have to send post query to yor app right to the /tglogin/ page.

P.S. Post query example on python:
`url = 'http://localhost:3000/tglogin/'
requests.post(url, data={'botCode': '4dferiu7', 'authToken': 'xpAn7j8sK5StelAp5iJ3cU9Ii7xDsR0q', \
  'tgId': 213456, 'username': '@tgusername'})`

**Comment by elie222** [comment]
I have a telegram bot built with meteor.

How do you send a post request from a telegram client to a telegram bot?

**Comment by kaskar2008** [comment]
You don't need to send a post request from a telegram client to a telegram bot. Your bot must send it to your meteor app when the message with `TGloginCode` will be recieved from some user.

**Comment by kaskar2008** [comment]
Should I close this issue or you didn't get the answer?
